/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#404754',
        'inverse-primary': '#c3c0ff',
        'tertiary': '#97000c',
        'on-tertiary-fixed-variant': '#93000b',
        'primary-fixed': '#e2dfff',
        'tertiary-container': '#c20b17',
        'surface-variant': '#dce2f7',
        'on-surface-variant': '#464555',
        'on-primary': '#ffffff',
        'primary': '#3525cd',
        'tertiary-fixed': '#ffdad6',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed': '#0f0069',
        'inverse-surface': '#293040',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#dce2f7',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#410002',
        'surface-tint': '#4d44e3',
        'inverse-on-surface': '#edf0ff',
        'on-tertiary-container': '#ffd1cc',
        'outline-variant': '#c7c4d8',
        'outline': '#777587',
        'surface-container-high': '#e1e8fd',
        'secondary-fixed': '#dce2f3',
        'on-secondary-fixed': '#151c27',
        'error': '#ba1a1a',
        'tertiary-fixed-dim': '#ffb4ab',
        'on-primary-fixed-variant': '#3323cc',
        'secondary-fixed-dim': '#c0c7d6',
        'error-container': '#ffdad6',
        'surface-dim': '#d3daef',
        'on-secondary-container': '#5e6572',
        'surface-container': '#e9edff',
        'surface-bright': '#f9f9ff',
        'on-error': '#ffffff',
        'surface-container-low': '#f1f3ff',
        'secondary': '#585f6c',
        'surface': '#f9f9ff',
        'secondary-container': '#dce2f3',
        'primary-container': '#4f46e5',
        'on-primary-container': '#dad7ff',
        'on-surface': '#141b2b',
        'background': '#f9f9ff',
        'on-background': '#141b2b',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Manrope', 'sans-serif'],
        'label': ['Manrope', 'sans-serif'],
        'display': ['Syne', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
    },
  },
  plugins: [],
}
